### ISSUE TITLE
Pan and PSN parameters not set

### ISSUE THREAD

**Issue by bando483** [CiscoISE/ciscoise-terraform-automation-aws-nodes#15] opened 2024-07-25 16:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

1.7.0

### AWS Provider Version

5.45.0

### Affected Resource(s)/Data Source(s)

NEW

### Terraform Configuration Files

```hcl
terraform.tvars is populated with all the requested parameters and EC2 instances are created
```

### Expected Behaviour

set DNS and NTP on terraform.tfvars.. and hostname

### Actual Behaviour

DEV-ISE-022/iseadmin#show run
interface GigabitEthernet 0
 ip address 10.56.35.114 255.255.255.0
 ipv6 enable
 ipv6 address autoconfig
!
ntp server 10.210.38.240
hostname DEV-ISE-022
icmp echo on
ip domain-name demo.local
ip default-gateway 10.56.35.1
ip name-server 10.210.38.240

**Comment by bando483** [comment] 2024-07-25 16:35
no parameter is set on machines (neither the NTP, nor the DNS and nor the hostname)

EC2 instances are reachable in SSH but the configuration is wrong

**Comment by bando483** [comment] 2024-07-25 16:39
it is strange since the iseadmin password is set and working, via aws console

**Comment by bando483** [comment] 2024-07-25 17:00
even the UTC+1 is not set.

once the deploy worked for me, and what I changed has been the instance type of PAN from m5.4xlarge to c5.4xlarge.

**Comment by bando483** [comment] 2024-07-25 17:28
tested again with full admin rights and the issue is still there

**Comment by bando483** [comment] 2024-07-25 20:29
I tested rolling back to m5.4xlarge but nothing changed... those parameters are not applied to configuration. honestly I'm stuck and I was near to deploy it in production, but I can't now. thanks for help

**Comment by bando483** [comment] 2024-07-26 13:21
I might have found the issue... 

time_zone         = "UTC+1"             # Enter a timezone

with 

time_zone         = "UTC"             # Enter a timezone the deploy works properly.

which is the correct syntax for time_zone?

**Comment by sudhanss** [comment] 2024-07-26 16:49
time_zone = "UTC" --> This is the right format to enter time_zone.

**Comment by sudhanss** [comment] 2024-07-26 16:55
Please ensure to double check terraform.tvars file is edited properly with right parameter and Deployment shall work. Also Please note terraform execution shows success upon creation of the all resources, For deployment formation we need to monitor state machine for successful execution.

Thanks for using the scripts, We will be happy to help in case of any issue while using the script and will also ensure the feedback and suggestions are implemented in upcoming release.

**Comment by sudhanss** [comment] 2024-07-28 20:16
Hi Alessio (@bando483) - Could you please confirm if we can close this issue as not a bug? As you have pointed out that after correcting time_zone variable in terraform.tfvar file, deployment worked as expected.

**Comment by bando483** [comment] 2024-07-28 20:43
Sorry I explained my need wrongly. I need to set up UTC+1.. which is the correct syntax to do that?
Inviato da iPhone

Il giorno 26 lug 2024, alle ore 18:49, Sudhanshu Sharma ***@***.***> ha scritto:

﻿
CAUTION! This message was sent from OUTSIDE of the company.
Please do not provide any confidential information or click on any link and attachment unless you recognize the sender.

time_zone = "UTC" --> This is the right format to enter time_zone.

**Comment by bando483** [comment] 2024-07-28 20:46
Hi

If you can address my question on UTC+1 correct syntax, then you can close the issue…

It is not a bug but a parameter set on terraform.tfvars
Inviato da iPhone

Il giorno 28 lug 2024, alle ore 22:16, Sudhanshu Sharma ***@***.***> ha scritto:

﻿
CAUTION! This message was sent from OUTSIDE of the company.
Please do not provide any confidential information or click on any link and attachment unless you recognize the sender.

Hi Alessio ***@***.***<https://github.com/bando483>) - Could you please confirm if we can close this issue as not a bug? As you have pointed out that after correcting time_zone variable in terraform.tfvar file, deployment worked as expected.

**Comment by sudhanss** [comment] 2024-07-29 05:21
for UTC+1 you can mention --> CET
Central European Time (CET) is UTC+1.

Please refer to below reference Cisco ISE guide for allowed time-zones - https://www.cisco.com/c/en/us/td/docs/security/ise/3-3/cli_guide/b_ise_CLI_Reference_Guide_33/b_ise_CLIReferenceGuide_33_chapter_011.html?bookSearch=true#wp2884933107

**Comment by bando483** [comment] 2024-07-29 07:19
I'm going to test it today

**Comment by bando483** [comment] 2024-07-29 12:15
you can close this topic... with CET it is fine

**Comment by sudhanss** [comment] 2024-07-29 13:21
Thanks for the confirmation. I am closing the ticket.

**Closed by sudhanss** 2024-07-29 13:21 UTC
Labels: question
